name: tests.yml

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '27'

      - name: Configurer Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Rendre gradlew exécutable
        run: chmod +x ./gradlew

      - name: Lancer les tests
        run: ./gradlew test

      - name: Publier le rapport de tests
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rapport-tests
          path: build/reports/tests/test/